/* Lenovo NEWIFI-MINI */

#define BOARD_PID		"ZBT-WE1826"
#define BOARD_NAME		"ZBT-WE1826"
#define BOARD_DESC		"ZBT-WE1826"
#define BOARD_VENDOR_NAME	"ZBT Limited"
#define BOARD_VENDOR_URL	"http://www.zbt.com/"
#define BOARD_MODEL_URL		"http://www.cctv.com/"
#define BOARD_BOOT_TIME		25
#define BOARD_FLASH_TIME	120
#undef BOARD_GPIO_BTN_RESET
#define BOARD_GPIO_BTN_WPS	13
#undef  BOARD_GPIO_BTN_WLTOG
#undef BOARD_GPIO_LED_ALL
#define BOARD_GPIO_LED_WIFI	72
#undef  BOARD_GPIO_LED_SW2G
#define BOARD_GPIO_LED_SW5G	50
#define BOARD_GPIO_LED_POWER	9
#define BOARD_GPIO_LED_LAN	55
#define BOARD_GPIO_LED_WAN	51
#define BOARD_GPIO_LED_USB	52
#undef  BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	0
#define BOARD_NUM_ANT_5G_TX	0
#define BOARD_NUM_ANT_5G_RX	0
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_HAS_EPHY_L1000	0
#define BOARD_HAS_EPHY_W1000	0
